### ISSUE TITLE
some questions about evaluate.py

### ISSUE THREAD

**Issue by vxgu86** [fpgasystems/spooNN#11]
I have some questions about this py file. thanks 
what does the VERBOSITY = 1or2 do?

and questions about the following five functions, what are theirs trying to do?
still thank you and sorry, I am newbie...

def computeThresholds(MatrixW, OutP, Wmax, bn_beta, bn_gamma, bn_mean, bn_variance, Mbit, Abit):
	return hex_thresholds

def computeFactors(MatrixW, OutP, Wmax, bn_beta, bn_gamma, bn_mean, bn_variance, Mbit):
	return hex_A, hex_B

def genereateHLSparams(layers_list, network_model, path_to_params, fw):
	f.write(hlsweights_file_content)
	f.close()

def generateConfig(layers_list, path_to_config):
	configFile.write(pragmas)
	configFile.write(network)
	configFile.close()
	return layers_list

def generateLayers(session, activation_bits, weight_bits, non_quantized_layers, frequency, FMpS_target):
	return json_out, layers_list, max_cycles

**Comment by kaankara** [comment]
- VERBOSITY just determines what to print while executing evaluate, for debugging purposes.
- computeThresholds and computeFactors are responsible for generating values to perform batchnorm or relu activation on the FPGA. This is a bit involved and if you want to understand this in depth I suggest looking at the HLS code and see how these values are used.
- generateHLSparams is the function where all weight values to be used in HLS are generated. Again, it is a bit more involved, but you probably don't need to change anything here.
- generateConfig creates a configuration file with layer specific parameters.
- generateLayers is to automate generating function calls which then can be integrated directly into HLS. The usage of this is optional.
