### ISSUE TITLE
what if I change the resolution to 1280*720

### ISSUE THREAD

**Issue by vxgu86** [fpgasystems/spooNN#12]
what if I change the resolution to 1280*720,  should I change all the net params?

**Comment by vxgu86** [comment]
aksing this becasue I notice that there are resize in the halfsqueezenet, if I resize the jpg and xml, then there are no difference between 640*480 and 640*360 and 1024*768?
the only question is that the resize of iou part, I have not understood this part, is there any thing I missed?

**Comment by kaankara** [comment]
Any image will be resized to 224x224 anyway, before it is fed into the neural network. So, the initial resolution can be higher than that, but you need to make use that the bounding box gets resized also correctly with the image. One helpful method is to display the image together with the bounding box after resizing and make sure the box is still in the correct place.
