### ISSUE TITLE
any idea about the max_pred max_h max_w?

### ISSUE THREAD

**Issue by vxgu86** [fpgasystems/spooNN#15]
what is the meanings of the following three variables?
				max_pred = objdetect[0, h, w]
					max_h = h
					max_w = w

and how do I know the classification of the object in halfsqueezenet?

**Comment by kaankara** [comment]
max_h and max_w are the coordinates with the grid cell that has the highest probability of containing the object. max_pred is the anchored bounding box that is predicted by that grid cell. Look at the loop around this portion: It just selects the grid cell with the highest prob. of containing the object.

**Comment by vxgu86** [comment]
the question  about the spooNN project, 

max_pred = objdetect[0, h, w]
max_h = h
max_w = w

I am asking this because these variables are 14*14 matrix of minus numbers like -3.21 -1.458 etc.
and I still have not get one point, how can I know which object is the bounding box detecting?

the number of classes also changed when I do my detecting, should I change sth else in the code?
