### ISSUE TITLE
the weights quantization

### ISSUE THREAD

**Issue by k-zhou08** [fpgasystems/spooNN#17]
if bitW == 1:
            with G.gradient_override_map({"Sign": "Identity"}):
                E = tf.stop_gradient(tf.reduce_mean(tf.abs(x)))
                return tf.sign(x) * E

I wonder how can you represent the weights with only 1 bit.  or you only use this during the training and when you dump the weights, you used other method to quantize the weight.

**Comment by kaankara** [comment]
The training enforces the weights to be in the set of {-Wmax, Wmax} per layer. When dumping the weights we can thus represent them using 1-bit and a high-precision value of Wmax, which is merged into the activation together with batch-norm. Check evaluate.py to see how this is done.

**Comment by k-zhou08** [comment]
![2019-03-27 15-59-15屏幕截图](https://user-images.githubusercontent.com/20692763/55059200-56f36e80-50a9-11e9-8f8b-6b6990886d0a.png)

I ran it on the HLS, and found the result is wrong, as shown in the attachment. the  python can give the right result.

**Comment by kaankara** [comment]
Did you manage to figure out what was wrong here? Maybe the input is not fed correctly?
