### ISSUE TITLE
magic number

### ISSUE THREAD

**Issue by theDweeb** [fpgasystems/spooNN#18]
## Allocate Buffers
MINIBATCH_SIZE = 4
height = 224
width = 224
pixel_bits = 24
pixels_per_line = **_384_**/pixel_bits
num_lines = int((height*width)/pixels_per_line)

in_buffer = xlnk.cma_array(shape=(MINIBATCH_SIZE*num_lines, 64), dtype=np.uint8)

fire1_num_out_lines = 28*28*MINIBATCH_SIZE
fire1_out_buffer = xlnk.cma_array(shape=(int(16*fire1_num_out_lines),), dtype=np.uint32)
fire2345_num_out_lines = 14*14*MINIBATCH_SIZE
fire2_out_buffer = xlnk.cma_array(shape=(int(16*fire2345_num_out_lines),), dtype=np.uint32)
fire3_out_buffer = xlnk.cma_array(shape=(int(16*fire2345_num_out_lines),), dtype=np.uint32)
bndboxes = xlnk.cma_array(shape=(int(MINIBATCH_SIZE),16), dtype=np.int32)

Hello, I was wondering where the number 384 came from? Thanks

**Comment by kaankara** [comment]
384 bits out of 512 bits (the bus width) contain the data. So, you get 16 pixels (384/24) per input line.
