### ISSUE TITLE
Vivado synth does not complete for mnist-cnn

### ISSUE THREAD

**Issue by elizamanelli** [fpgasystems/spooNN#19]
Hi,
I'm trying to rebuild the whole bitstream and run all the steps described in the mnist-cnn READ_ME. The training and HLS implementation and IP generation work fine. (Somehow the utilization is surprisingly big, it would be wonderful if you could provide an utilization report for your generated IP.)

While running the make_bitstream.sh skript it never finishes - it's always "waiting for impl1 to finish". 
I'm running Vivado 2017.4 so that's not what is causing the problem. To investigate I reproduced the full make_bistream and procsys script in the Vivado GUI (using the tcl-command line). There everything works without any errors until I launch the run "launch_runs impl_1 -to_step write_bitstream -jobs 2". This one never finishes. In the report files generated I can see, that every process finishes synthesis except the procsys_DoCompute_0_0_synth1.
I have attached the Log of this file. [synth_log.txt](https://github.com/fpgasystems/spooNN/files/3161531/synth_log.txt) It finishes the basic synthesis but does not even start the post-synthesis steps. In the other log files there follow a section like:

> Synthesis finished with 0 errors, 0 critical warnings and 63 warnings.
Synthesis Optimization Runtime : Time (s): cpu = 00:00:40 ; elapsed = 00:00:58 . Memory (MB): peak = 1687.059 ; gain = 209.527 ; free physical = 234033 ; free virtual = 249739
Synthesis Optimization Complete : Time (s): cpu = 00:00:49 ; elapsed = 00:01:19 . Memory (MB): peak = 1687.059 ; gain = 507.840 ; free physical = 234033 ; free virtual = 249739
INFO: [Project 1-571] Translating synthesized netlist
INFO: [Project 1-570] Preparing netlist for logic optimization
INFO: [Opt 31-138] Pushed 0 inverter(s) to 0 load pin(s).
INFO: [Project 1-111] Unisim Transformation Summary:
No Unisim elements were transformed.
INFO: [Common 17-83] Releasing license: Synthesis
83 Infos, 106 Warnings, 0 Critical Warnings and 0 Errors encountered.
synth_design completed successfully
synth_design: Time (s): cpu = 00:00:51 ; elapsed = 00:01:21 . Memory (MB): peak = 1687.059 ; gain = 526.941 ; free physical = 234002 ; free virtual = 249708
INFO: [Common 17-1381] The checkpoint '/home/developer/project_2/project_2.runs/procsys_xbar_0_synth_1/procsys_xbar_0.dcp' has been generated.
INFO: [Coretcl 2-1482] Added synthesis output to IP cache for IP /home/developer/project_2/project_2.srcs/sources_1/bd/procsys/ip/procsys_xbar_0/procsys_xbar_0.xci
INFO: [Coretcl 2-1174] Renamed 7 cell refs.
INFO: [Common 17-1381] The checkpoint '/home/developer/project_2/project_2.runs/procsys_xbar_0_synth_1/procsys_xbar_0.dcp' has been generated.
INFO: [runtcl-4] Executing : report_utilization -file procsys_xbar_0_utilization_synth.rpt -pb procsys_xbar_0_utilization_synth.pb
report_utilization: Time (s): cpu = 00:00:00.08 ; elapsed = 00:00:00.10 . Memory (MB): peak = 1711.070 ; gain = 0.000 ; free physical = 234104 ; free virtual = 249813
INFO: [Common 17-206] Exiting Vivado at Wed May  8 13:21:58 2019...

I also tried to leave out all the build directives and just run in default mode - but that produced the same output.
Do you have any idea what could be the problem?

**Comment by kaankara** [comment]
Hi, unfortunately I could not reproduce this issue. Did you make any changes to the original hls code?
