### ISSUE TITLE
Why multiply 0x882065?

### ISSUE THREAD

**Issue by yunlong12** [fpgasystems/spooNN#22]
Hi Kaan, in spooNN/halfsqueezenet/deploy/halfsqueezenet-objdetect.ipynb, I cannot understand the following code,
float_bndboxes *= 0x882065

What is 0x882065? and why do you multipy float_bndboxes with it?
Thanks.

**Comment by kaankara** [comment]
That is a hacky way of applying the factors for the last layer (bounding box drawing). You can check in halfsqueezenet/training/halfsqueezenet-params.h, factorA17 has this value.
