### ISSUE TITLE
hls_stream.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by JanashreeA** [fpgasystems/spooNN#23]
g++  -I../../hls-nn-lib/ -I/include/ -std=c++0x -Wall -Wno-unknown-pragmas -Wall -Wno-unknown-pragmas -Wno-unused-variable -g mnist-cnn-1W5A.cpp -o t_1W5A -lpthread
In file included from ../../hls-nn-lib/hls-nn-lib.h:19:0,
                 from mnist-cnn-1W5A.cpp:24:
../../hls-nn-lib/layer-conv2d.h:19:24: fatal error: hls_stream.h: No such file or directory
compilation terminated.
make: *** [mnist-cnn-1W5A] Error 1

**Comment by kaankara** [comment]
Please see the instructions:
"Export XILINX_VIVADO_HLS to point to your installation: $ export XILINX_VIVADO_HLS=/path/to/Xilinx/Vivado/2017.4"
