### ISSUE TITLE
deorefa and evaluate import errors

### ISSUE THREAD

**Issue by xilinxJAM** [fpgasystems/spooNN#3]
Hi I am trying to run your example flow for the Pynq. 

When I run the training script I get errors for the dorefa and evaluate imports.

from dorefa import get_dorefa
from evaluate import *

DoReFa I found and took from https://github.com/tensorpack/tensorpack/tree/master/examples/DoReFa-Net

Is this correct and where should I get evaluate from?

**Comment by kaankara** [comment]
Hi,
1) I would not recommend running the training on a PYNQ. This will be extremely slow. I recommend using an x86 machine, ideally with a GPU attached.
2) The modified dorefa script is already included in spooNN (hls-nn-lib/training). Please execute "$ export PYTHONPATH=/path/to/spooNN/hls-nn-lib/training:$PYTHONPATH", as described in the steps for training.

**Comment by xilinxJAM** [comment]
Thanks, that works, I missed that line in the setup. I am running the training on a x86, with a GPU. I reworded my question as misleading.
Thanks again & congratulations on DAC2018

**Comment by kaankara** [comment]
Awesome, I am glad it works.

**Comment by IDKhow2do** [comment]
Im a green hand,and I try to run this on my windows pc,but I found the command upon a linux instruction,so i just missed it,maybe I should make out what the instrcut means first.
