### ISSUE TITLE
some problems with the pynq-vivado project

### ISSUE THREAD

**Issue by vxgu86** [fpgasystems/spooNN#8]
in the readme, you said 
"You can generate that by opening the pynq-vivado project with Vivado. Open the block design procsys. Then do File->Export->Export Block Design. This is the same file that is readily available at ./scripts/procsys.tcl  "
but I cannot find the pynq-vivado project, what do you mean by this?

**Comment by kaankara** [comment]
Please follow the steps in 3. RTL and bitstream generation. There the pynq-vivado project is created to build the bitstream.
