### ISSUE TITLE
procedure when running ./scripts/make_bitstream.sh '/home/lthpc/spooNN/mnist-cnn' 

### ISSUE THREAD

**Issue by vxgu86** [fpgasystems/spooNN#9]
I have put the board files in the path like ...Vivado/2017.4/data/boards/board_files/pynq-z2/A.0...
and switch PYNQ-Z1_C.xdc to pynq-z2_v1.0.xdc due to the warinings like 
"WARNING: [Vivado 12-584] No ports matched 'led_green'. [/home/lthpc/spooNN/mnist-cnn/scripts/PYNQ-Z1_C.xdc:25]"

but the errors are still unchanged as follows:
some suggestions please?? 
thanks!!

****** Vivado v2017.4 (64-bit)
  **** SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
  **** IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
    ** Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.

source procsys_wrapper.tcl -notrace
Command: link_design -top procsys_wrapper -part xc7z020clg400-1
Design is defaulting to srcset: sources_1
Design is defaulting to constrset: constrs_1
INFO: [Project 1-479] Netlist was created with Vivado 2017.4
INFO: [Device 21-403] Loading part xc7z020clg400-1
INFO: [Project 1-570] Preparing netlist for logic optimization
Parsing XDC File [/home/lthpc/spooNN/mnist-cnn/scripts/pynq-z2_v1.0.xdc]
Finished Parsing XDC File [/home/lthpc/spooNN/mnist-cnn/scripts/pynq-z2_v1.0.xdc]
INFO: [Opt 31-138] Pushed 0 inverter(s) to 0 load pin(s).
**CRITICAL WARNING: [Project 1-486] Could not resolve non-primitive black box cell 'procsys' instantiated as 'procsys_i' [/home/lthpc/spooNN/mnist-cnn/output/pynq-vivado/pynq-vivado.srcs/sources_1/bd/procsys/hdl/procsys_wrapper.v:16]**
INFO: [Project 1-111] Unisim Transformation Summary:
No Unisim elements were transformed.

5 Infos, 0 Warnings, 1 Critical Warnings and 0 Errors encountered.
link_design completed successfully
link_design: Time (s): cpu = 00:00:14 ; elapsed = 00:00:40 . Memory (MB): peak = 1450.480 ; gain = 287.824 ; free physical = 2348 ; free virtual = 89361
Command: opt_design -directive Explore
INFO: [Vivado_Tcl 4-136] Directive used for opt_design is: Explore
Attempting to get a license for feature 'Implementation' and/or device 'xc7z020'
INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xc7z020'
Running DRC as a precondition to command opt_design

Starting DRC Task
INFO: [DRC 23-27] Running DRC with 8 threads
**ERROR: [DRC INBB-3] Black Box Instances: Cell 'procsys_i' of type 'procsys' has undefined contents and is considered a black box.  The contents of this cell must be defined for opt_design to complete successfully.**
INFO: [Project 1-461] DRC finished with 1 Errors
INFO: [Project 1-462] Please refer to the DRC report (report_drc) for more information.
ERROR: [Vivado_Tcl 4-78] Error(s) found during DRC. Opt_design not run.

Time (s): cpu = 00:00:00.25 ; elapsed = 00:00:00.41 . Memory (MB): peak = 1515.512 ; gain = 65.031 ; free physical = 2345 ; free virtual = 89358
INFO: [Common 17-83] Releasing license: Implementation
11 Infos, 0 Warnings, 1 Critical Warnings and 2 Errors encountered.
opt_design failed
ERROR: [Common 17-39] 'opt_design' failed due to earlier errors.

INFO: [Common 17-206] Exiting Vivado at Fri Nov 16 11:44:02 2018...
[Fri Nov 16 11:44:03 2018] impl_1 finished
wait_on_run: Time (s): cpu = 00:01:27 ; elapsed = 00:02:23 . Memory (MB): peak = 1326.684 ; gain = 3.996 ; free physical = 2804 ; free virtual = 89818
INFO: [Common 17-206] Exiting Vivado at Fri Nov 16 11:44:03 2018...

**Comment by kaankara** [comment]
If you have a PYNQ Z2, I am not sure if it is that straightforward to use the scripts in the repo. It probably requires some other changes. The build flow in this repo has been only tested for PYNQ Z1. You might not use the scripts as is, but it should not be that difficult to start a project from scratch, add the HLS-packaged IP and so forth.
